include: package:lint/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
    avoid_positional_boolean_parameters: false
    depend_on_referenced_packages: false
    always_use_package_imports: false

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.gen.dart
    - lib/**.gr.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
  errors:
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
    invalid_annotation_target: ignore
