include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_positional_boolean_parameters: false

analyzer:
  exclude:
    - lib/generated/**
    - lib/**.g.dart
    - lib/**.gen.dart
    - lib/**.gr.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
  errors:
    missing_return: error
    missing_required_param: error
    parameter_assignments: error
