import 'package:flutter/material.dart';

import '../../common/general/button/primary_button.dart';
import '../../common/general/default_appbar.dart';
import '../../util/extensions/context_extensions.dart';
import '../../util/extensions/iterable_extensions.dart';
import '../../util/theme_styles.dart';
import '../widgets/onboarding_background.dart';

class SaveSeedPhraseRoute extends MaterialPageRoute<void> {
  SaveSeedPhraseRoute() : super(builder: (_) => const SaveSeedPhraseScreen());
}

/// !!! Here displays only 12 words
class SaveSeedPhraseScreen extends StatefulWidget {
  const SaveSeedPhraseScreen({Key? key}) : super(key: key);

  @override
  State<SaveSeedPhraseScreen> createState() => _SaveSeedPhraseScreenState();
}

class _SaveSeedPhraseScreenState extends State<SaveSeedPhraseScreen> {
  final words = [
    'accept',
    'terms',
    'save',
    'confirm',
    'phrase',
    'decentralization',
    'lucky',
    'good',
    'pencil',
    'accept',
    'terms',
    'save',
  ];

  @override
  Widget build(BuildContext context) {
    final localization = context.localization;
    final themeStyle = context.themeStyle;

    return OnboardingBackground(
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: const DefaultAppBar(),
        body: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(localization.save_seed_phrase, style: themeStyle.styles.appbarStyle),
              const SizedBox(height: 16),
              Text(
                // TODO: change text
                'It is the series of words generated by your cryptocurrency wallet that give you access to the crypto associated with that wallet',
                style: themeStyle.styles.basicStyle,
              ),
              const SizedBox(height: 32),
              Expanded(
                child: SingleChildScrollView(
                  child: Row(
                    children: [
                      Expanded(
                        child: Column(
                          children: words
                              .getRange(0, 6)
                              .mapIndex((word, i) => _textPair(word, i + 1, themeStyle))
                              .toList(),
                        ),
                      ),
                      Expanded(
                        child: Column(
                          children: words
                              .getRange(6, 12)
                              .mapIndex((word, i) => _textPair(word, i + 7, themeStyle))
                              .toList(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              PrimaryButton(
                text: localization.copy_words,
                onPressed: () {},
                isTransparent: true,
              ),
              const SizedBox(height: 12),
              PrimaryButton(
                text: localization.confirm_seed_saved,
                onPressed: () {},
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _textPair(String word, int index, ThemeStyle themeStyle) {
    final style = themeStyle.styles.basicStyle;
    final colors = themeStyle.colors;
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Row(
        children: [
          SizedBox(
            width: 28,
            child: Text(
              '$index.',
              style: style.copyWith(color: colors.textSecondaryTextButtonColor),
            ),
          ),
          Expanded(
            child: Text(word, style: style, textAlign: TextAlign.left),
          ),
        ],
      ),
    );
  }
}
