import "../android/fastlane/Fastfile"
import "../ios/fastlane/Fastfile"

$ios_path="../ios/fastlane"
$android_path="../android/fastlane"

add_extra_platforms(platforms: [:all])
default_platform(:all)

before_all do
  if is_ci
    update_fastlane
  end
end
