$ios_path="."

default_platform(:ios)

platform :ios do
  desc "Deploy a new build to the TestFlight"
  lane :deploy_testflight do |options|
    Dir.chdir($ios_path) do
      api_key = app_store_connect_api_key(
        key_id: "Z9SXC3WYGA",
        issuer_id: "5cf5ca66-f161-4f94-b09c-d0df4af7d0a1",
        key_filepath: "fastlane/AuthKey_Z9SXC3WYGA.p8",
      )
      upload_to_testflight(
        ipa: "../build/ios/ipa/ever_wallet.ipa",
        skip_waiting_for_build_processing: true,
        api_key: api_key,
        changelog: "#{options[:changelog_string]}"
        )
    end
  end

  desc "Deploy a new build to the FAD"
  lane :deploy_fad do |options|
    Dir.chdir($ios_path) do
      firebase_app_distribution(
        app: "1:1017783238389:ios:a0ab19a124c910702e4fbc",
        groups: "qa",
        ipa_path: "../build/ios/ipa/ever_wallet.ipa",
        service_credentials_file: "../fastlane/FirebaseADKey.json",
        release_notes: "#{options[:changelog_string]}"
      )
    end
  end

  desc "Assure there is correct iOS certs and profiles"
  lane :match_assure do
    Dir.chdir($ios_path) do
      match(type: "appstore", readonly: is_ci)
      match(type: "development", readonly: is_ci)
      match(type: "adhoc", readonly: is_ci)
    end
  end

  desc "Register new devices already added through devportal to adhoc and development certs and profiles"
  lane :match_new_devices do
    Dir.chdir($ios_path) do
      match(type: "development", force_for_new_devices: true)
      match(type: "adhoc", force_for_new_devices: true)
    end
  end
end
