$android_path="."

default_platform(:android)

platform :android do
  desc "Deploy a new build to the Google Play Internal channel"
  lane :deploy_google_play_internal do
    Dir.chdir($android_path) do
      upload_to_play_store(
        track: "internal",
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        changes_not_sent_for_review: true
      )
    end
  end

  desc "Deploy a new build to the FAD"
  lane :deploy_fad do
    Dir.chdir($android_path) do
      firebase_app_distribution(
        app: "1:1017783238389:android:23c9e07bee6cc2ef2e4fbc",
        groups: "qa",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        service_credentials_file: "../fastlane/FirebaseADKey.json"
      )
    end
  end
end
